<?php /** Static case study page content. @package Woo_Dev_Studio */ ?>
<main id="main" class="site-main case-study">
<section class="case-hero"><div class="container case-hero__inner"><p class="eyebrow"><span></span> Featured case study</p><h1>Vellure.<br><em>Commerce, refined.</em></h1><div class="case-hero__details"><p>A considered WooCommerce experience for a modern skincare brand—built to feel calm, convert confidently and scale without friction.</p><dl class="case-meta"><div><dt>Client</dt><dd>Vellure</dd></div><div><dt>Industry</dt><dd>Beauty &amp; wellness</dd></div><div><dt>Year</dt><dd>2025</dd></div></dl></div></div></section>
<section class="case-showcase" aria-label="Vellure online store preview"><div class="container"><div class="case-browser"><div class="case-browser__bar"><span></span><span></span><span></span><small>vellure.com</small></div><div class="case-browser__screen"><p>Vellure</p><div class="case-product" aria-hidden="true"><span></span><strong>V</strong></div><div><small>NEW FORMULA / DAILY RITUAL</small><h2>Quiet care<br>for radiant skin.</h2><span class="case-shop-link">Shop the collection&nbsp; ↗</span></div></div></div></div></section>
<section class="section case-intro"><div class="container case-intro__grid"><p class="eyebrow"><span></span> The brief</p><div><h2>A premium store with<br><em>purpose in every detail.</em></h2><p>Vellure needed more than a beautiful storefront. The brand required a fast, flexible commerce platform that made complex product education effortless and gave its internal team room to grow.</p></div></div></section>
<section class="case-results"><div class="container"><p class="eyebrow"><span></span> The outcome</p><div class="case-results__grid"><article><strong>42<em>%</em></strong><p>increase in mobile conversion</p></article><article><strong>1.3<em>s</em></strong><p>average storefront load time</p></article><article><strong>28<em>%</em></strong><p>lift in average order value</p></article></div></div></section>
<section class="section case-story"><div class="container case-story__grid"><div><span class="case-story__number">01</span><h2>The challenge</h2></div><div><p class="case-story__lead">Turn a tactile, editorial brand into a digital experience without sacrificing speed or clarity.</p><p>The previous store made discovery difficult and hid the value behind each formula. On mobile, long paths and an inflexible product system created friction at the moment customers were ready to buy.</p></div><div><span class="case-story__number">02</span><h2>The solution</h2></div><div><p class="case-story__lead">A custom WooCommerce theme that balances storytelling with a focused path to purchase.</p><p>We created a modular editorial system, clear product comparison and a streamlined cart experience. Reusable content blocks let the Vellure team launch campaigns quickly while keeping every page distinctly on brand.</p></div></div></section>
<section class="case-gallery" aria-label="Project highlights"><div class="container case-gallery__grid"><div class="case-gallery__tile case-gallery__tile--violet"><div class="case-mobile"><small>Vellure</small><span class="case-mobile__bottle">V</span><strong>Find your<br>daily ritual.</strong></div></div><div class="case-gallery__tile case-gallery__tile--lime"><p>Built around<br><em>the product.</em></p><div class="case-pack" aria-hidden="true">V</div></div></div></section>
<section class="section case-tech"><div class="container case-tech__grid"><div><p class="eyebrow"><span></span> What we delivered</p><h2>Thoughtful design.<br><em>Solid technology.</em></h2></div><ul><li>UX &amp; commerce strategy</li><li>Custom WordPress theme</li><li>WooCommerce development</li><li>Editorial content system</li><li>Performance optimisation</li><li>Analytics &amp; launch support</li></ul></div></section>
<?php get_template_part('template-parts/home/contact'); ?>
</main>
